"""Generate docs/API.md from the package docstrings.

Kept deliberately dependency-free (no Sphinx) so that the API reference can
be regenerated in CI with the same environment that runs the tests:

    python docs/gen_api.py
"""
import dataclasses
import importlib
import inspect
import pathlib

MODULES = ["config", "network", "agents", "simulation", "metrics",
           "invariants", "economics", "metamorphic", "reference", "benchmark", "sweep", "viz"]
OUT = pathlib.Path(__file__).parent / "API.md"


def signature(obj):
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return "(...)"


def first_paragraph(doc):
    if not doc:
        return "_No description._"
    lines = []
    for line in inspect.cleandoc(doc).splitlines():
        if not line.strip() and lines:
            break
        lines.append(line.strip())
    return " ".join(lines)


def render() -> str:
    """The reference as a string; deterministic across Python versions."""
    import scfsim

    out = [f"# SCFSim API reference (v{scfsim.__version__})", "",
           "Generated by `python docs/gen_api.py` — do not edit by hand.", ""]
    for name in MODULES:
        mod = importlib.import_module(f"scfsim.{name}")
        out += [f"## `scfsim.{name}`", "", first_paragraph(mod.__doc__), ""]
        members = [(n, o) for n, o in vars(mod).items()
                   if not n.startswith("_")
                   and getattr(o, "__module__", None) == mod.__name__]
        classes = [(n, o) for n, o in members if inspect.isclass(o)]
        funcs = [(n, o) for n, o in members if inspect.isfunction(o)]
        for n, obj in classes:
            out += [f"### `class {n}`", "", first_paragraph(obj.__doc__), ""]
            fields = getattr(obj, "__dataclass_fields__", {})
            if fields:
                out += ["| field | type | default |", "|---|---|---|"]
                for fname, f in fields.items():
                    if f.default is not dataclasses.MISSING:
                        default = repr(f.default)
                    elif f.default_factory is not dataclasses.MISSING:
                        factory = f.default_factory
                        default = f"{getattr(factory, '__name__', 'factory')}()"
                    else:
                        default = "required"
                    typ = getattr(f.type, "__name__", str(f.type))
                    out.append(f"| `{fname}` | `{typ}` | `{default}` |")
                out.append("")
        for n, obj in funcs:
            out += [f"### `{n}{signature(obj)}`", "",
                    first_paragraph(obj.__doc__), ""]
    return "\n".join(out)


def main(out: pathlib.Path = OUT) -> None:
    text = render()
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out} ({text.count(chr(10)) + 1} lines)")


if __name__ == "__main__":
    main()
